apiVersion: v2
name: data-sync-operator-chart
description: A Helm chart to distribute the project data-sync-operator
type: application
version: 1.0.8
appVersion: "0.1.0"
icon: "https://example.com/icon.png"
