apiVersion: v2
name: data-sync-operator
description: A Helm chart to distribute the project data-sync-operator
type: application
# x-release-please-start-version
version: 0.1.0
appVersion: "0.1.0"
# x-release-please-end
icon: "https://example.com/icon.png"
