{{- if .Values.metrics.enable }}
apiVersion: v1
kind: Service
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: data-sync-operator
        control-plane: controller-manager
    name: data-sync-operator-controller-manager-metrics-service
    namespace: {{ .Release.Namespace }}
spec:
    ports:
        - name: https
          port: {{ .Values.metrics.port }}
          protocol: TCP
          targetPort: {{ .Values.metrics.port }}
    selector:
        app.kubernetes.io/name: data-sync-operator
        control-plane: controller-manager
{{- end }}
