# This rule is not used by the project data-sync-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the crd.pelotech.ot.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: data-sync-operator
    app.kubernetes.io/managed-by: kustomize
  name: vmdiskimage-editor-role
rules:
- apiGroups:
  - crd.pelotech.ot
  resources:
  - vmdiskimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.pelotech.ot
  resources:
  - vmdiskimages/status
  verbs:
  - get
