# This rule is not used by the project data-sync-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over crd.pelotech.ot.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: data-sync-operator
    app.kubernetes.io/managed-by: kustomize
  name: vmdiskimage-admin-role
rules:
- apiGroups:
  - crd.pelotech.ot
  resources:
  - vmdiskimages
  verbs:
  - '*'
- apiGroups:
  - crd.pelotech.ot
  resources:
  - vmdiskimages/status
  verbs:
  - get
