apiVersion: crd.pelotech.ot/v1aplha1
kind: VMDiskImage
metadata:
  labels:
    app.kubernetes.io/name: data-sync-operator
    app.kubernetes.io/managed-by: kustomize
  name: vmdiskimage-sample
spec:
  secretRef: "secret-1"
  sourceType: blank
  diskSize: "1Mi"
  snapshotClass: "daily-snapshots"
