{{- if .Values.rbacHelpers.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: data-sync-operator
    name: data-sync-operator-vmdiskimage-editor-role
rules:
    - apiGroups:
        - crd.pelotech.ot
      resources:
        - vmdiskimages
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
    - apiGroups:
        - crd.pelotech.ot
      resources:
        - vmdiskimages/status
      verbs:
        - get
{{- end }}
